version: '3'

services:
  app:
    container_name: authentication_app
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'

  db:
    image: mongo
    container_name: authentication_db
    ports:
      - 27017:27017
