version: '3'

services:
  authentication_app:
    container_name: authentication_app
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    depends_on:
      - authentication_db
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - fastpay-network
    ports:
      - '3001:3001'

  authentication_db:
    image: mongo
    container_name: authentication_db
    networks:
      - fastpay-network
    ports:
      - 27017:27017

networks:
  fastpay-network:
    external: true
